# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# If 

trigger:
- master

pool:
  #vmImage: 'ubuntu-latest'
  name: 'PASU'

steps:

- script: |
    export PP_INSTALLDIRS=$(build.installdirs)
    echo Building PolyPackage
    make clean
    make all
  displayName: 'Building PolyPackage'

- script: |
    export PP_INSTALLDIRS=$(build.installdirs)
    echo Installing PolyPackage
    make install
  displayName: 'Copy PolyPackage to Installation Directories'
  condition: ne(variables['build.installdirs'], NULL)

